Repository fusionjs/fusion-plugin-apollo, pull requests merged in 2018-11, with the labels that each got.

#126 Release v1.4.1-0
  package.json
Labels: release

#128 Add support for passing in a custom render function
  README.md
  package.json
  src/__tests__/exports.js
  src/index.js
  yarn.lock
Labels: feature

#129 Release v1.5.0-0
  package.json
Labels: release

#130 Release v1.5.0
  package.json
Labels: release

#131 Upgrade dependendencies
  package.json
  yarn.lock
Labels: bugfix, greenkeeping

#133 Upgrade deps
  .npmrc
  package.json
  yarn.lock
Labels: greenkeeping

#134 Release v1.5.1
  package.json
Labels: release

#136 Fix flow issues with apollo client type
  flow-typed/npm/apollo-client_v2.x.x.js
  flow-typed/npm/flow-bin_v0.x.x.js
  flow-typed/npm/prettier_v1.x.x.js
  flow-typed/npm/react-apollo_v2.x.x.js
  flow-typed/npm/redux_v4.x.x.js
  package.json
  src/__tests__/exports.js
  src/index.js
Labels: bugfix

#138 Release v1.5.2-0
  package.json
Labels: release

#137 Upgrade dependencies
  .npmrc
  package.json
  yarn.lock
Labels: greenkeeping
