Repository fusionjs/fusion-plugin-apollo, pull requests merged in 2018-10, with the labels that each got.

#114 Upgrade dependency versions
  .flowconfig
  package.json
  yarn.lock
Labels: greenkeeping

#116 Add support for gql macro
  README.md
  src/__tests__/exports.js
  src/index.js
Labels: feature

#117 Release v1.4.0-0
  package.json
Labels: release

#124 Implement CI for multiple node versions
  .buildkite/pipeline.yml
  Dockerfile
  docker-compose.yml
Labels: refactor
