Repository fusionjs/fusion-plugin-apollo, pull requests merged in 2019-04, with the labels that each got.

#174 Release v2.0.0-4
  package.json
Labels: release

#175 Allow to use an external graphQL server
  README.md
  src/__tests__/server.node.js
  src/plugin.js
Labels: bugfix

#177 Merge logic from fusion-apollo-universal-client, export multiple plugins
  README.md
  docs/migrations/00159.md
  package.json
  src/__tests__/exports.js
  src/__tests__/integration.node.js
  src/__tests__/server.node.js
  src/apollo-client/__tests__/exports.js
  src/apollo-client/__tests__/index.js
  src/apollo-client/__tests__/local-state.js
  src/apollo-client/index.js
  src/index.js
  src/plugin.js
  src/server.js
  yarn.lock
Labels: feature

#178 Release v2.0.0-5
  package.json
Labels: release

#179 Update flow to 0.96 and fix flow error
  package.json
  src/plugin.js
  yarn.lock
Labels: bugfix, greenkeeping

#182 Release v2.0.0-6
  package.json
Labels: release

#183 Move cache extraction into after await next
  src/__tests__/server.node.js
  src/plugin.js
Labels: bugfix

#184 Release v2.0.0-7
  package.json
Labels: release

#185 Use unescape exported from fusion-core
  src/plugin.js
Labels: bugfix

#186 Release v2.0.0-8
  package.json
Labels: release
