Repository fusionjs/fusion-plugin-apollo, pull requests merged in 2019-03, with the labels that each got.

#147 Return DocumentNode when calling `gql`
  src/index.js
Labels: bugfix

#158 Migrate to a plugin based api
  README.md
  package.json
  src/__tests__/exports.js
  src/__tests__/server.node.js
  src/index.js
  yarn.lock
Labels: breaking

#160 Release v1.6.1-0
  package.json
Labels: release

#161 Release v1.6.1
  package.json
Labels: release

#159 Refactor into a render plugin rather than an app wrapper
  .buildkite/pipeline.yml
  .github/ISSUE_TEMPLATE.md
  Dockerfile
  README.md
  docker-compose.yml
  docs/migrations/00159.md
  package.json
  src/__tests__/exports.js
  src/__tests__/integration.node.js
  src/__tests__/server.node.js
  src/flow/flow-fixture.js
  src/index.js
  src/plugin.js
  src/tokens.js
  yarn.lock
Labels: breaking

#162 Release v2.0.0-0
  package.json
Labels: release

#164 Fix tree shaking
  src/__tests__/exports.js
  src/plugin.js
Labels: bugfix

#165 Release v2.0.0-1
  package.json
Labels: release

#168 Add support for graphql middleware
  README.md
  package.json
  src/__tests__/server.node.js
  src/plugin.js
  src/tokens.js
  yarn.lock
Labels: feature

#169 Release v2.0.0-2
  package.json
Labels: release

#170 Simplify usage of schema token
  README.md
  package.json
  src/__tests__/integration.node.js
  src/plugin.js
  yarn.lock
Labels: bugfix

#171 Revert "Add support for graphql middleware"
  README.md
  package.json
  src/__tests__/server.node.js
  src/plugin.js
  src/tokens.js
  yarn.lock
Labels: bugfix

#172 Release v2.0.0-3
  package.json
Labels: release
